# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Tom-Inge Larsen
# Generated on: 09.11.2018

@{
    RootModule        = 'Get-PSGoodFirstIssue.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '146d8d1a-f3f9-4925-84c0-16681e27963a'
    Author            = 'Tom-Inge Larsen'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Tom-Inge Larsen. All rights reserved.'
    Description       = 'Gets a random issue from gihub.com/PowerShell/PowerShell that is tagged with Up-for-Grabs'
    FunctionsToExport = @()
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

